version: "3.8"
services:
  lp-db:
    image: "mongo:4"
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  lp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile-server-prod
    ports:
      - "4000:4000"
    env_file:
      - ./packages/server/.env.preprod
    depends_on:
      - lp-db
    environment:
      - MONGO_CONNECTION=mongodb://lp-db:27017
  lp-front:
    build:
      context: .
      dockerfile: docker/Dockerfile-front
      args:
        GQL_URL: "http://localhost:4000/"
        TOKEN_TTL: 7
        NODE_ENV: "test"
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
