version: "3.8"
services:
  lp-db:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./.env
  lp-server:
    build: ./packages/server
    ports:
      - "4000:4000"
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    env_file:
      - ./packages/server/.env
    depends_on:
      - lp-db
volumes:
  data:   