version: "3.8"
services:
  lp-front:
    build:
      context: .
      dockerfile: docker/Dockerfile-front-prod
    ports:
      - '8080:80'
    env_file:
      - ./packages/front/.env
    stdin_open: true
    tty: true
