version: "3.8"
services:
  lp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile-server-prod
    ports:
      - "4000:4000"
    env_file:
      - ./packages/server/.env
  lp-front:
    build:
      context: .
      dockerfile: docker/Dockerfile-front
      args:
        - GQL_URL=/data/graphql
        - TOKEN_TTL=7
        - NODE_ENV=production
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
    depends_on:
      - lp-server
