FROM node:18-alpine3.17

WORKDIR /app

COPY package.json /app

COPY yarn.lock /app/

COPY lerna.json /app

COPY packages/server /app/packages/server

COPY packages/shared /app/packages/shared

RUN yarn install --production --frozen-lockfile

RUN yarn build:server

RUN cp -a packages/server/dist /app/dist

RUN rm -rf /app/packages/server

EXPOSE 4000

CMD ["node", "dist/app.js"]