FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock lerna.json /app/

COPY packages/server /app/packages/server

COPY packages/shared /app/packages/shared

RUN yarn install --production --frozen-lockfile

RUN yarn build:server

RUN rm -rf /app/packages/server/src

RUN chown -R  node:node /app/

USER node

WORKDIR /app/packages/server

CMD ["node", "dist/app.js"]