name: Release Monorepo

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type to pass to Lerna (patch, minor, major) or auto for conventional commits'
        required: true
        default: auto
        type: choice
        options:
          - patch
          - minor
          - major
          - auto

  push:
    branches:
      - main

jobs:
  linting-and-testing:
    uses: ./.github/workflows/common-jobs.yml
    secrets:
      JWT_SECTET: ${{ secrets.JWT_SECTET }}
      AUDIO_ENDPOINT: ${{ secrets.AUDIO_ENDPOINT }}
      IMG_ENDPOINT: ${{ secrets.IMG_ENDPOINT }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  cypress:
    uses: ./.github/workflows/cypress.yml
    needs: linting-and-testing
    secrets:
      JWT_SECTET: ${{ secrets.JWT_SECTET }}
      AUDIO_ENDPOINT: ${{ secrets.AUDIO_ENDPOINT }}
      IMG_ENDPOINT: ${{ secrets.IMG_ENDPOINT }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  release:
    runs-on: ubuntu-22.04
    needs: [linting-and-testing]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'
      - uses: ./.github/actions/setup-yarn
      - name: Configure Git user
        run: |
          git config --global user.email "ci-bot@yourdomain.com"
          git config --global user.name "CI Bot"
      - name: Run Lerna Release Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "auto" ]; then
            yarn release --yes
          else
            yarn release -- --${{ github.event.inputs.release_type }} --yes
          fi
  docker:
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    needs: release
